[2025-04-20T23:38:44.535+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:37:12.138079+00:00 [queued]>
[2025-04-20T23:38:44.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:37:12.138079+00:00 [queued]>
[2025-04-20T23:38:44.557+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-20T23:38:44.585+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt> on 2025-04-20 23:37:12.138079+00:00
[2025-04-20T23:38:44.598+0000] {standard_task_runner.py:60} INFO - Started process 205 to run task
[2025-04-20T23:38:44.601+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_csv_to_snowflake', 'run_dbt', 'manual__2025-04-20T23:37:12.138079+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ingest_bronze_dag.py', '--cfg-path', '/tmp/tmp9ccowouw']
[2025-04-20T23:38:44.607+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask run_dbt
[2025-04-20T23:38:44.693+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:37:12.138079+00:00 [running]> on host baa4deac6175
[2025-04-20T23:38:44.836+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_bronze_csv_to_snowflake' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T23:37:12.138079+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T23:37:12.138079+00:00'
[2025-04-20T23:38:44.838+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T23:38:44.840+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/edu_dbt && dbt run --full-refresh --profiles-dir /opt/***/edu_dbt/profiles']
[2025-04-20T23:38:44.861+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T23:38:47.910+0000] {subprocess.py:93} INFO - [0m23:38:47  Running with dbt=1.7.2
[2025-04-20T23:38:47.917+0000] {subprocess.py:93} INFO - [0m23:38:47  Encountered an error:
[2025-04-20T23:38:47.918+0000] {subprocess.py:93} INFO - Runtime Error
[2025-04-20T23:38:47.919+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /opt/***/edu_dbt/dbt_project.yml
[2025-04-20T23:38:47.921+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2025-04-20T23:38:47.922+0000] {subprocess.py:93} INFO - 
[2025-04-20T23:38:48.925+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-20T23:38:48.948+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-20T23:38:48.959+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_bronze_csv_to_snowflake, task_id=run_dbt, execution_date=20250420T233712, start_date=20250420T233844, end_date=20250420T233848
[2025-04-20T23:38:48.994+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task run_dbt (Bash command failed. The command returned a non-zero exit code 2.; 205)
[2025-04-20T23:38:49.040+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-20T23:38:49.106+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
