[2025-04-20T23:27:30.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:24:00.416543+00:00 [queued]>
[2025-04-20T23:27:30.908+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:24:00.416543+00:00 [queued]>
[2025-04-20T23:27:30.910+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-04-20T23:27:30.963+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt> on 2025-04-20 23:24:00.416543+00:00
[2025-04-20T23:27:30.978+0000] {standard_task_runner.py:60} INFO - Started process 259 to run task
[2025-04-20T23:27:30.986+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_csv_to_snowflake', 'run_dbt', 'manual__2025-04-20T23:24:00.416543+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/ingest_bronze_dag.py', '--cfg-path', '/tmp/tmp4idj8wdu']
[2025-04-20T23:27:30.996+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask run_dbt
[2025-04-20T23:27:31.093+0000] {task_command.py:423} INFO - Running <TaskInstance: ingest_bronze_csv_to_snowflake.run_dbt manual__2025-04-20T23:24:00.416543+00:00 [running]> on host d1aafe94e42c
[2025-04-20T23:27:31.216+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_bronze_csv_to_snowflake' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T23:24:00.416543+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T23:24:00.416543+00:00'
[2025-04-20T23:27:31.221+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T23:27:31.224+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/edu_dbt && dbt run --full-refresh']
[2025-04-20T23:27:31.246+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T23:27:34.057+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-04-20T23:27:34.058+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-04-20T23:27:34.059+0000] {subprocess.py:93} INFO - 
[2025-04-20T23:27:34.060+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/home/***/.dbt' does not exist.
[2025-04-20T23:27:34.288+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-20T23:27:34.300+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-20T23:27:34.306+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ingest_bronze_csv_to_snowflake, task_id=run_dbt, execution_date=20250420T232400, start_date=20250420T232730, end_date=20250420T232734
[2025-04-20T23:27:34.324+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task run_dbt (Bash command failed. The command returned a non-zero exit code 2.; 259)
[2025-04-20T23:27:34.337+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-20T23:27:34.355+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
